### ISSUE TITLE
Get method descriptor from API instead of a regex

### ISSUE THREAD

**Issue by histausse** [micronoyau/dexcaliburn#2]
Don't do this:

https://github.com/micronoyau/dexcaliburn/blob/3b08bb7e26a399c1168d638b7ee156a1d12b9c48/src/frida-scripts/index.ts#L111-L117

Use:
 - https://developer.android.com/reference/java/lang/reflect/Method#getDeclaringClass()
 -  https://developer.android.com/reference/java/lang/reflect/Method#getReturnType()
 - https://developer.android.com/reference/java/lang/reflect/Method#getParameterTypes()
 - https://developer.android.com/reference/java/lang/Class#getCanonicalName()

**Comment by micronoyau** [comment]
Done
